version: '3.8'

services:
  # Microservicio A: Gesti√≥n de Usuarios y Notas
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "5000:5000"  
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./auth_service:/app  
    networks:
      - spotify_net

  # Microservicio B: Conector con Spotify
  music_service:
    build: ./music_service
    container_name: music_service
    ports:
      - "5001:5000"  
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./music_service:/app
    networks:
      - spotify_net

# Red privada para que se hablen entre ellos
networks:
  spotify_net:
    driver: bridge